{% set name = "lxml-html-clean" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lxml_html_clean-{{ version }}.tar.gz
  sha256: c9df91925b00f836c807beab127aac82575110eacff54d0a75187914f1bd9d8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - lxml

test:
  imports:
    - lxml_html_clean
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fedora-python/lxml_html_clean/
  doc_url: https://lxml-html-clean.readthedocs.io/
  summary: HTML cleaner from lxml project
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
