{% set name = "lxml-html-clean" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lxml_html_clean-{{ version }}.tar.gz
  sha256: c355c5e738d27dfb8fc474896ab5973b4c54d6c22f472582bee8357081989276

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7
    - lxml

test:
  imports:
    - lxml_html_clean
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fedora-python/lxml_html_clean/
  doc_url: https://lxml-html-clean.readthedocs.io/
  summary: HTML cleaner from lxml project
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
